# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deputado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1024)),
                ('nome_civil', models.CharField(blank=True, max_length=254, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino')], default='m', max_length=1)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('falecimento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('sigla', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='deputado',
            name='profissao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deputados', to='parlamentar.Profissao'),
        ),
    ]
