# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('parlamentar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legislatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mandato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deputado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandatos', to='parlamentar.Deputado')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandatos', to='base.Estado')),
                ('legislatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandatos', to='trabalho.Legislatura')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_presente', models.BooleanField(default=False)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('deputado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='parlamentar.Deputado')),
            ],
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('numero', models.PositiveIntegerField()),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='presenca',
            name='sessao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='trabalho.Sessao'),
        ),
        migrations.AddField(
            model_name='mandato',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabalho.Partido'),
        ),
    ]
