# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_municipio'),
        ('trabalho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('mandato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='trabalho.Mandato')),
            ],
        ),
        migrations.CreateModel(
            name='GastoTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=2048)),
                ('media_despesa', models.DecimalField(decimal_places=2, max_digits=20)),
                ('media_mensal', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='InfoEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_obtencao', models.DateField()),
                ('nome_empresa', models.CharField(max_length=512)),
                ('data_abertura', models.DateField()),
                ('logradouro', models.CharField(max_length=1024)),
                ('numero', models.CharField(max_length=16)),
                ('complemento', models.CharField(max_length=64)),
                ('cep', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(max_length=64)),
                ('efr', models.CharField(max_length=2048, verbose_name='Ente Federativo Responsável')),
                ('data_situacao_cadastral', models.DateField()),
                ('situacao_especial', models.CharField(blank=True, max_length=2048, null=True)),
                ('capital_social', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ip_colaborador', models.CharField(max_length=15)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informacoes', to='base.Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='NaturezaJuridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18)),
                ('razao_social', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representantes', to='cap.PessoaFisica')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=15)),
                ('ip_colaborador', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sociedade', to='cap.InfoEmpresa')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sociedade', to='cap.PessoaFisica')),
            ],
        ),
        migrations.CreateModel(
            name='SocioQualificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('descricao', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDespesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='socio',
            name='qualificacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sociedade', to='cap.SocioQualificacao'),
        ),
        migrations.AddField(
            model_name='representante',
            name='qualificacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representantes', to='cap.SocioQualificacao'),
        ),
        migrations.AddField(
            model_name='representante',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representantes', to='cap.Socio'),
        ),
        migrations.AddField(
            model_name='infoempresa',
            name='situacao_cadastral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informacoes', to='cap.Situacao'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='tipo_despesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cap.GastoTipo'),
        ),
    ]
